name: Node.js Package

on:
  push:
    paths:
      - 'package.json'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      
      # 添加其他构建步骤
      
      - name: Check version changes
        id: check_version
        run: echo "::set-output name=version_changed::$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} | grep package.json)"

      - name: Publish to npm
        if: steps.check_version.outputs.version_changed == 'package.json'
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git tag -a v${{ steps.get_version.outputs.version }} -m "Release version ${{ steps.get_version.outputs.version }}"
          git push --tags
          npm publish
